name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-${{ github.ref }}-${{ hashFiles('**/Cargo.lock') }}

    # IncrementalBuildが機能しないので、以下3ステップでファイルのタイムスタンプをgitから復元する
    # https://zenn.dev/kt3k/articles/d557cc874961ab
    - name: Install Python
      uses: actions/setup-python@v2
    - name: Install git-restore-mtime
      run: sudo apt-get update && sudo apt-get install git-restore-mtime -y
    - name: Restore mtime
      run: git restore-mtime

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
